Taskfile.yml, scaffold/Taskfile.yml, tasks/drupal.yml
This is a bit of a grab-bag of a PR, but the actual number of changed lines is fairly small:
1. Moves `Taskfile.yml` into a subdirectory so we can eventually add one for this project if we want. It's symlinked for now since the installer plugin still looks into the root.
2. Makes it clear the build command is _for production_ use. Otherwise, having a basic "composer install" is not actually useful since we need to run that first to get the taskfile for fresh git checkouts.
3. Switches from checking the existence of generated files to hashing them. Also checks the installed.json file to see if we are including dev dependencies or not.
4. Spells out and namespaces the maintenance mode commands, to make it easier for new users to understand.
=> Improvements to composer and Drupal commands

scaffold/ddev/task-command.sh, src/TaskfileInstallerPlugin.php
…includes
```
{
"type": "path",
"version": "dev-main",
"url": "/path/to/drainpipe",
"options": {
"symlink": false
}
},
```
=> Issue #9: Add a helper for ddev to run task easily

.github/workflows/test-production-build.yml, composer.json, tests/fixtures.drainpipe-test-build/composer.json
I went to add Drainpipe to The Daily Report, thinking it would be good to do that _before_ we do the Drupal 9 upgrade. However, drainpipe requires `symfony/yaml` 4, and Drupal 8.9 is on Symfony 3. It wouldn't surprise me if we have inherited projects that need to update to Drupal 9 but have some cleanups to do first, even past the official Drupal 8 EOL.
Also, I got to learn about how GitHub actions handles matrix builds, and they're pretty good 👍 
https://github.com/Lullabot/drainpipe/pull/37/checks?check_run_id=3667614911 shows testing against Drupal 8.9, and https://github.com/Lullabot/drainpipe/pull/37/checks?check_run_id=3667615016 tests against 9.2.
=> Allow Symfony 3 for Drupal 8 sites

src/BinaryInstallerPlugin.php
- Run `composer require lullabot/drainpipe:dev-justafish/upgrade-task-3.8.0` on a project using Drainpipe (you might need to first remove `drainpipe-dev` if it has a dependency on `dev-main`
- Run `./vendor/bin/task --version` and verify Task has been upgraded to v3.8.0
=> Upgrade Task to 3.8.0

tasks/drupal.yml, tests/fixtures.drainpipe-test-build/Taskfile.yml
Fingerprints locally generated files and their sources to prevent
unnecessary work. Also renames the command to composer:production and
adds a composer:development and install task too.
See Issue #36
=> feat: Enable sources/generates/status for composer

README.md, tasks/drupal.yml, tasks/pantheon.yml
Allows it to be overridden like so:
```
cmds:
- task: drupal:import-db
vars: {DB_DIR: "/var/www/html/files/private"}
```
=> Make db export directories customisable

scaffold/github/actions/pantheon/review/action.yml, scaffold/github/workflows/PantheonReviewApps.yml
See https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions?learn=dependency_version_updates&learnProduct=code-security#changing-github_token-permissions
=> Move set Drainpipe env to it's own run step and fix dependabot GITHUB_TOKEN permissions

scaffold/github/actions/pantheon/clone-env/action.yml, scaffold/github/actions/pantheon/push/action.yml, scaffold/github/actions/pantheon/review/action.yml, scaffold/github/actions/pantheon/update/action.yml, scaffold/github/workflows/PantheonReviewApps.yml, scaffold/github/workflows/PantheonReviewAppsDDEV.yml
also removes the need to provide a site-id as this can be fetched via Terminus
=> Pantheon GitHub Actions: Add a Clone Environment command

scaffold/github/actions/pantheon/clone-env/action.yml
Removes the environment wipe and adds `--delete` to the rsync command
=> Don't wipe environments when cloning between Pantheon sites

.github/workflows/TestGitHubActions.yml, scaffold/github/actions/common/ddev/action.yml, tests/fixtures/drainpipe-test-github-actions/.ddev/config.yaml, tests/fixtures/drainpipe-test-github-actions/Taskfile.yml, tests/fixtures/drainpipe-test-github-actions/composer.json
This also disables the composer cache until https://github.com/drud/ddev/pull/3697 is released as this command is breaking setups which are using existing environment variables
Additionally adds a test for the Install DDEV GitHub Action
=> Allow DDEV version to be customised

scaffold/gitlab/PantheonReviewApps.gitlab-ci.yml
=> Unquoted variable causing Pantheon Multidev Cleanup failure

README.md
Today @mtift and I were testing out a "from-scratch" install, and were confused when drainpipe-dev scaffolding wasn't being added. This PR replaces the `composer require...` step with a link to the docs, and splits it out into headings since we no longer have a single code block to follow.
=> Link to drainpipe-dev for installation docs

README.md, metapackages/javascript/esbuild.js
While trying to define the JS assets in a new theme I found out that setting the variable `DRAINPIPE_JAVASCRIPT` in `Taskfile.yml` wasn't working properly: whatever I set in there it'd export it in another directory right below `docroot`.
I set:
```
DRAINPIPE_JAVASCRIPT: |
docroot/themes/custom/my_theme/src/script.js:docroot/themes/custom/my_theme/src/script.min.js
```
And instead of exporting it into `docroot/themes/custom/my_theme/src/script.min.js`, it was creating the files into `docroot`, ignoring the target path.
@hawkeyetwolf helped me coming up with this possible solution, forcing the definition of the `outbase` value, and now the source path set is being used for the target too.
But while reading the comments about the [limitation to provide separate …
=> Force the Javascript target definition

scaffold/github/actions/common/ddev/action.yml
Available as of 1.19.2 of DDEV https://github.com/drud/ddev/releases/tag/v1.19.2
=> Enable the composer cache directory for GitHub Actions

README.md, scaffold/github/actions/pantheon/setup-terminus/action.yml, scaffold/github/workflows/PantheonReviewApps.yml, scaffold/gitlab/Pantheon.gitlab-ci.yml, scaffold/gitlab/gitlab-ci.example.yml
This PR just makes the [Terminus Secrets plugin](https://github.com/pantheon-systems/terminus-secrets-plugin) available by default when installing Drainpipe
=> Support Terminus plugins in Github and Gitlab

scaffold/tugboat/config.example.yml
I'm not sure if it's new in the latest Tugboat image, but the $DOCROOT symlink already exists and points to `/var/www/html.original`. So when trying to use this config on a recent client project, I needed to remove the `[ -d ]` ("is file") shell test and overwrite the existing `$DOCROOT` symlink.
=> Override default $DOCROOT symlink

scaffold/ddev/env, src/ScaffoldInstallerPlugin.php
After fixing this functionality and then pulling it into an actual project it caused a lot of things to break. This modifies the scaffolder to only bring the compose file in if `.env` exists already.
See:
https://github.com/docker/compose/issues/3560
https://github.com/docker/compose/pull/3955
https://github.com/docker/compose/issues/9181
https://github.com/Lullabot/lullabot.com-d8/pull/2252/checks?sha=c015942c2e232261d91883a240048cb40726f19d
=> Only copy the docker compose env support in if a .env file exists

.github/workflows/TestEnv.yml, README.md, composer.json, scaffold/Taskfile.yml, scaffold/ddev/docker-compose.env-file.yaml, scaffold/ddev/env, scaffold/env/env, scaffold/env/env.defaults, scaffold/env/load.environment.php, src/ScaffoldInstallerPlugin.php, tests/fixtures/env/Taskfile-dotenv.yml, tests/fixtures/env/Taskfile-no-dotenv.yml
When pulling the added .env support into an existing project it blew everything up due to an `.env` file not being explicitly created by the CI or build process (which it shouldn't have to be!)
=> Fixes .env support

scaffold/gitignore/common.gitignore
Drupal comes with `development.services.yml`, which is a different filename pattern than what's used for settings files (e.g., `settings.local.php`). 
Optionally, we could unignore _both_ patterns if folks prefer that.
=> Unignore services files that start with wildcard

.github/workflows/composer-plugin.yml, .github/workflows/test-production-build.yml, scaffold/github/workflows/PantheonReviewApps.yml, scaffold/github/workflows/PantheonReviewAppsDDEV.yml
I didn't notice any regressions on a client project after upgrading the `actions/cache` action from v2 to v3. It cleared 4 warnings that were present in the UI.
=> Upgrade the 'cache' github action to v3 to clear warnings about nodejs version

README.md
I was taking a look at https://github.com/Lullabot/drainpipe/pull/151#event-7824247398 to see what changes I need in order to make dotenv work, and noticed what I think is a change in the filename that got pushed separately after that PR merged? Not 100% sure though.
=> Update path in dotenv instructions

metapackages/sass/gulp.js, tasks/sass.yml
Fixes https://github.com/Lullabot/drainpipe/issues/176
=> Specify drainpipe-sass script interpreter

tasks/deploy.yml, tasks/snapshot.yml
When running in CI, the commit command can generate tens of thousands of log lines for each file committed. This isn't very useful, and can start to lag browsers.
This PR adds `--quiet` and also switches `-m` to `--message` following https://architecture.lullabot.com/adr/20211006-avoid-command-aliases/.
=> Quiet git commit commands

metapackages/sass/gulpfile.js, metapackages/sass/package.json
The Chokidar version is old and broken on Macs https://github.com/gulpjs/glob-watcher/issues/49
To test:
- 'yarn unplug @lullabot/drainpipe-sass`
- Replace `.yarn/unplugged/@lullabot-drainpipe-sass-npm<some other stuff>/node_modules/@lullabot/drainpipe-sass` with the new `gulpfile.js` and `package.json`
- Run `ddev yarn`
- Try and save a file multiple times and see if sass watch picks up on it
=> Add usePolling to sass watch

scaffold/gitignore/common.gitignore, tasks/test.yml
prettier is currently creating an empty folder in `node_modules`.
This folder conflicts with other tasks like `assets`, that expects that ´node_modules` is not present to run yarn commands.
See https://github.com/prettier/prettier/issues/13032
=> Specify prettier cache location to avoid secondary effects

drainpipe-dev/scaffold/phpcs.xml
https://architecture.lullabot.com/adr/20211201-use-strict-types-in-php-code/
=> Force to Use strict types in PHP code

.github/workflows/TestFunctional.yml, drainpipe-dev/config/nightwatch.conf.js, drainpipe-dev/scaffold/nightwatch/example.nightwatch.js, tasks/test.yml, tests/local-test.sh
Upgrading your project will require you to:
- Remove `nightwatch-accessibility`
- Add `nightwatch-axe-verbose`
- Swap `.initAccessibility()` for ` .axeInject()` e.g.
```
browser
.axeInject()
.axeRun('body')
```
- If using Yarn Berry, `.yarnrc.yml` will need to contain the following:
```
packageExtensions:
"nightwatch@*":
dependencies:
ws: "*"
lodash: "*"
```
- Other package managers should add `lodash` manually to `devDependencies`
=> Fixes Nightwatch integration for Nightwatch v3.1.0

.github/workflows/TestGitHubActions.yml, README.md, tasks/deploy.yml
Deploy task summary says that it accepts a "push parameter to push or not the code to the remote repository.
However, it pushes the code even if this flag is not set to true.
This PR removes the extra push done before the flag checkin.
Also changes the if clause because https://github.com/go-task/task/issues/609 is already fixed.
Finally the command usage example is modified to reflect the actual task behavior
=> Fix incosistency in deploy.yml file

tasks/test.yml
This is a followup from #223 
When running `task test:autofix`, the unwanted `node_modules` folder is created and new execution of other tasks that checks the existence of this folder, like `task sass:compile` fail.
This can be mitigated removing manually the `node_modules` before executing the command, but this solution, avoids the folder generation
=> Avoid creation of unwanted node_modules folder as part of test:autofix

scaffold/pantheon/settings.pantheon.php, scaffold/tugboat/settings.tugboat.php.twig
They should match "branch preview" at https://architecture.lullabot.com/adr/20210609-environment-indicator/.
=> Update tugboat environment indicator colours to match ADR

scaffold/tugboat/settings.tugboat.php.twig
The preview only exists after it's built. That means if you're trying to bootstrap Drupal during a build (database updates, config imports, etc) the database settings won't work.
As well, I removed the file check because it's only checking for itself.
=> Fix TUGBOAT_PREVIEW_ID not existing in build step

.github/workflows/TestStatic.yml, drainpipe-dev/composer.json, tasks/test.yml
This lets callers override test directories, as asked for in #267.
Since this is really task functionality, I only added a test for the YAML directories since that seemed to be the simplest to test.
In doing that I discovered something surprising. The symfony yaml library now also ships a `yaml-lint` command, which takes precedence over the one we were using. Since `j13k/yaml-lint` used symfony under the hood, I just removed the dependency.
=> Convert variables to support defaults with override #267

scaffold/github/actions/pantheon/review/action.yml
Improves the waiting mechanism after a deployment to Pantheon.
- Waits up to 5 minutes; otherwise, exits with an error.
- Exits with an error if the state differs from `pending` or `succeeded`.
- When the status is `succeeded`, the script continues as usual.
#159
=> #150 wait for Pantheon deployment

scaffold/tugboat/steps/1-init.sh.twig
=> Issue #410: Install the redis PHP extension in Tugboat

scaffold/github/actions/common/setup-ssh/action.yml
Looks like the variable syntax in the github ssh action isn't right.
=> Fix variables in setup-ssh GitHub action

.github/workflows/TestBinaryInstaller.yml, src/BinaryInstaller.php
Here's the test failing for commit 53f88b0 https://github.com/Lullabot/drainpipe/actions/runs/8286318726/job/22676024562
Fixes #164 and #135
=> Add a test for the binary installer and fix error when upgrading task binary

README.md, drainpipe-dev/src/DevBinaryInstallerPlugin.php, src/BinaryInstaller.php, src/BinaryInstallerPlugin.php
=> Issue #129: Wrong architecture for binaries downloaded on ARM Macs

.github/workflows/TestComposerLockDiff.yml, .github/workflows/TestFunctional.yml, .github/workflows/TestMetapackages.yml, .github/workflows/TestPHPUnit.yml, .github/workflows/TestStatic.yml, .github/workflows/TestTugboat.yml, scaffold/github/workflows/ComposerLockDiff.yml, scaffold/github/workflows/PantheonReviewApps.yml, scaffold/github/workflows/PantheonReviewAppsDDEV.yml
v3 actions are using node 16, which is EOL, giving some warnings.
This updates:
- actions/upload-artifact
- actions/download-artifact
- actions/cache
- actions/checkout
The artifacts need to be renamed on upload, as they aren't merged by default anymore. See https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md
I've let different artifacts, if we still want to merge the test results is doable, but not sure if we want that.
=> Issue #385: Update actions/upload-artifact and actions/download-artifact to v4

README.md
Missing the step to archive the _Ready to release_ column in the project board.
=> Updated missing step in release docs

scaffold/github/actions/common/setup-ssh/action.yml
I'm using this action with a GitHub workflow with `container: drupalci/php-8.1-apache`.
The setup-ssh action doesn't work.
This fixes it.
- Use `apt-get` command.
- Run `apt-get update` to ensure package lists are up to date.
- Use `-y` on install so it works non-interactively.
=> Fix setup-ssh action apt install commands.

.github/workflows/DrainpipeDev.yml, drainpipe-dev/.github/workflows/repo-lockdown.yml
* Make the checkout fallback to `origin/main` in case the branch or tag doesn't exist. This will support if we want to push more branches to drainpipe-dev in the future for testing or anything.
* Adjust the repo-lockdown workflow to run once a week instead of every hour, we were running into secondary rate limits: https://github.com/Lullabot/drainpipe-dev/actions/runs/8707015439
=> Fix drainpipe-dev workflow when run as a tag

src/BinaryInstaller.php
This PR is from https://github.com/Lullabot/drainpipe/pull/114 and:
1. Pulls out a method to document our if logic.
2. We don't need the second file_exists() call. The first one will return if it does not exist, which means to get to the last `||` statement the file must exist.
=> Extract a needs download method in the binary installer

composer.json
Fixes https://github.com/Lullabot/drainpipe/issues/541
* Drops support for Drush v10. Drupal 10 requires at least v11.
* Drops support for Symfony v3, v4, and v5. Drupal 10 requires at least v6.2.
* Drops support for Twig 2. Drupal 10 requires at least v3.
* Adds support for Drush v13.
* Adds support for Symfony v7.
* Fixes that `ext-json` was listed twice.
Once this is merged we can close https://github.com/Lullabot/drainpipe/pull/451 or re-run it.
=> Drop all Drupal 9 dependency versions

drainpipe-dev/composer.json
https://github.com/Lullabot/drainpipe/pull/544 was still failing widely because I forgot there was a drainpipe-dev dependency that I didn't also update in https://github.com/Lullabot/drainpipe/pull/542
=> Update drainpipe-dev to remove old Symfony dependency versions

src/ScaffoldInstallerPlugin.php
Fixes #369 
* Adds a way for environment indicator settings to be injected into ddev.
Not sure if this is the best approach but I followed how settings.php gets changed to include tugboat. I decided against generating a different settings.*.php file for ddev because I couldn't see a clean way to include it when needed and exclude it when its not.
=> Issue #369: Inject environment indicators into DDEV settings

README.md
* lerna not learna (helps address https://github.com/Lullabot/drainpipe/issues/560)
* Updates docs about drainpipe-dev release management
=> Update docs on release process

README.md
=> Issue #567: Remove TOC from README

README.md, tasks/pantheon.yml
- #336 
- Allow site environment to be parameterized in pantheon:fetch-db.
=> Issue #336: Allow site environment to be parameterized in pantheon:fetch-db.

.tugboat/steps/1-init.sh
fixes: #605 
Tugboat builds for Drainpipe have been failing ever since Drupal 10.3.x was released.
Upon investigation it showed that the [sessions table is no longer part of install schema](https://www.drupal.org/node/3431286) and because of that `drush sql:sanitize` fails. This [has been fixed in Drush 13](https://github.com/drush-ops/drush/blob/13.x/src/Commands/sql/sanitize/SanitizeSessionsCommands.php) and is awaiting a stable release, it will also be [backported to Drush 12](https://github.com/drush-ops/drush/issues/6041).
To unblock all Drainpipe work until this gets fixed upstream I propose we pin Tugboat builds for Drainpipe to Drupal 10.2.7.
=> Issue #605: Pin Drupal version on Tugboat

tasks/drupal.yml
- #519 
- Fix drupal:import-db and drupal:export-db don't compress data.
=> Issue #519: Fix drupal:import-db and drupal:export-db don't compress data.

drainpipe-dev/bin/drainpipe-twig-linter
fixes: #615 
The automatic twig linting throws a fatal error when the Storybook module is present, as the static tests don't bootstrap Drupal to discover twig extensions. Since bootstrapping Drupal is expensive, instead check and load the twig extension manually.
=> feat(twig): support storybook twig extension in linting

.github/workflows/TestBinaryInstaller.yml, .github/workflows/TestComposerLockDiff.yml, .github/workflows/TestDDEV.yml, .github/workflows/TestEnv.yml, .github/workflows/TestFunctional.yml, .github/workflows/TestGitHubActions.yml, .github/workflows/TestMetapackages.yml, .github/workflows/TestPHPUnit.yml, .github/workflows/TestStatic.yml, .github/workflows/TestTugboat.yml, .github/workflows/composer-plugin.yml, .github/workflows/test-production-build.yml, .tugboat/config.yml, drainpipe-dev/composer.json, drainpipe-dev/scaffold/.twig-cs-fixer.dist.php, scaffold/phpunit-testtraits.xml, scaffold/phpunit.xml, tasks/test.yml, tests/fixtures/phpunit/testmodule/modules/testsubmodule/tests/src/Functional/UserCreateTest.php, tests/fixtures/phpunit/testmodule/modules/testsubmodule/tests/src/FunctionalJavascript/UserPasswordResetTest.php, tests/fixtures/phpunit/testmodule/modules/testsubmodule/tests/src/Unit/PermissionAccessCheckTest.php, tests/fixtures/phpunit/testmodule/tests/src/Functional/UserCreateTest.php, tests/fixtures/phpunit/testmodule/tests/src/FunctionalJavascript/UserPasswordResetTest.php, tests/fixtures/phpunit/testmodule/tests/src/Unit/PermissionAccessCheckTest.php, tests/local-test.sh
- Replace sserbin/twig-linter with vincentlanglet/twig-cs-fixer/ - sserbin/twig-linter depends on an old version of symfony/console and core is adopting this new package at some point https://www.drupal.org/project/drupal/issues/3284817 - it also has a much better extension mechanism which will help if something like #615 comes up again
- Update Pantheon settings for Drupal 11
- Update PHPUnit configurations and tests for Drupal 11
- Fix mysterious yarn issues with DDEV
=> Issue #638: Fix all our tests

tasks/test.yml
Only test the custom folder in modules and themes, to prevent linting contrib.
Re #655
=> Limit linted twig directories

.github/workflows/TestTugboat.yml, .tugboat/config.drainpipe-override.yml, .tugboat/config.yml, scaffold/tugboat/config.yml.twig
Fixes URLs with parameters for visual diffs in  .tugboat/config.drainpipe-override.yml
=> Output php configurations without escaping them #625

tasks/snapshot.yml
If you run a command like `task snapshot:archive o=archive.tar.xz`, the archive gets created in `/tmp/<something>`. As a caller, you don't know what `<something>` is so you can't get the archive. This can be worked around if you use an absolute path for `o=`, but this PR should fix it so relative paths work too.
=> Fix creating archives in the temporary directory and not the cwd

.github/workflows/TestGitHubActions.yml, drainpipe-dev/src/DevBinaryInstallerPlugin.php, src/BinaryInstallerPlugin.php, tasks/github.yml
Uses binaries instead of NPX. See #220
=> ISSUE-220: do not use npx for action validator, use binaries

metapackages/javascript/CHANGELOG.md, metapackages/javascript/package.json, metapackages/sass/CHANGELOG.md, metapackages/sass/package.json
- @lullabot/drainpipe-javascript@0.0.6
- @lullabot/drainpipe-sass@0.1.4
=> chore(release): publish

scaffold/Taskfile.yml, tests/fixtures/drainpipe-task-upgrade/Taskfile.yml
Adds a check that fails if there are errors in the Status Report page.
=> ISSUE-398: fail if there are red lines in the Status Report admin page

tasks/drupal.yml
=> fix(#743): "drupal:db-import" frozen if $DB_DIR/db.sql.gz already exists

renovate.json
Resolves: #797 
This pull request includes updates to the `renovate.json` file to manage package dependencies more effectively. The most important changes involve adding specific rules for certain packages and setting version constraints.
Dependency management updates:
* Added a rule to disable updates for `lullabot/drainpipe` and `lullabot/drainpipe-dev` packages.
* Added a rule to allow versions `^11`, `^12`, and `^13` for the `drush/drush` package.
* Added a rule to allow versions `^6` and `^7` for packages matching the pattern `^symfony/`.
=> Issue #797: improving renovate config to support ranges and ignoring drainpipe releases.

drainpipe-dev/scaffold/phpcs.xml.dist
It's common to have one or more `settings.local.php` files defined in your Drupal project. These are typically `.gitignore`'d and are completely and totally just for local development. They never need to be checked with `phpcs` and will often turn up common phpcs errors like the following for an unused variable:
```
[test:phpcs] FILE: /var/www/html/web/sites/default/settings.local.php
[test:phpcs] ----------------------------------------------------------------------
[test:phpcs] FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
[test:phpcs] ----------------------------------------------------------------------
[test:phpcs]  14 | WARNING | Unused variable $theme_dev_mode.
[test:phpcs] ----------------------------------------------------------------------
```
This change ignores all …
=> Ignore phpcs for settings.local.php

src/ScaffoldInstallerPlugin.php, tests/src/Unit/ScaffoldInstallerPluginTest.php
resolves: https://github.com/Lullabot/drainpipe/issues/752
The logic to extract the Redis image version from `.ddev/docker-compose.redis.yaml` only supported one format, resulting in incorrect or unknown versions being assigned to the configuration in some setups.
DDEV has changed the way Redis images are defined in different versions:
- **In [`v1.2.3`](https://github.com/ddev/ddev-redis/blob/v1.2.3/docker-compose.redis.yaml)**, the image is defined as:
```yaml
image: redis:${REDIS_TAG:-6-bullseye}
```
- **In [v2.0.2](https://github.com/ddev/ddev-redis/blob/v2.0.2/docker-compose.redis.yaml)**, the image is defined as:
```yaml
image: ${REDIS_DOCKER_IMAGE:-redis:7}
```
Updated the image parsing logic to support both patterns:
* `${REDIS_DOCKER_IMAGE:-redis:7}`
* …
=> Issue #752: Fix redis image name for tugboat.

.drainpipeignore, .gitattributes, .gitignore
Reverts Lullabot/drainpipe#840
Fixes #769 for real using .gitattributes to ignore the `drainpipe-dev` folder instead of .gitignore, which I realized afterwards will prevent you from making changes on a local checkout that can be committed.
See https://git-scm.com/docs/gitattributes#_export_ignore
=> Issue #769: Use gitattributes to remove drainpipe-dev

.tugboat/steps/2-update.sh, scaffold/tugboat/settings.tugboat.php.twig, scaffold/tugboat/steps/2-update.sh.twig
Fixes https://github.com/Lullabot/drainpipe/issues/866
=> Add skip_permissions_hardening setting flag to ensure Tugboat builds keep the sites/default directory writable

.github/workflows/DrainpipeDev.yml, drainpipe-dev/composer.json
Resolves https://github.com/Lullabot/drainpipe/issues/650
I have tested this with https://github.com/davereid/drainpipe and https://github.com/davereid/drainpipe-dev, which you can see was able to successfully push the latest tag release with this updated workflow:
- https://github.com/davereid/drainpipe-dev/releases/tag/v1.0.2
- https://github.com/davereid/drainpipe/actions/workflows/DrainpipeDev.yml
- https://github.com/davereid/drainpipe-dev/actions/workflows/release.yml
The problem was I was creating both a branch and a tag with the same name, then running `git push origin ${{ github.ref_name }}` and it didn't know to resolve the tag or the branch to push, so it failed.
This also gets rid of creating the release here in the workflow and letting the drainpipe-dev workflow create it …
=> Issue #650: Fix drainpipe-dev tag push and allow phpunit v11 to fix composer conflicts

.github/workflows/TestAcquia.yml
https://github.com/Lullabot/drainpipe/actions/workflows/TestAcquia.yml has been consistently failing:
```
[Error](https://github.com/Lullabot/drainpipe/actions/runs/16150343553/workflow)
the `uses' attribute must be a path, a Docker image, or owner/repo@ref
```
=> Fix uses error in TestAcquia.yml

renovate.json
- #797  
- Changes the Renovate configuration for Symfony packages, so the range strategy is set to `update-lockfile`, in order to keep ranges not modified by Renovate.
=> Issue #797: Change range strategy to update-lockfile for Symfony packages

tasks/drupal.yml
- #876 
Changes the order of cache rebuild and database update commands in the task `drupal:update`, to match what is suggested in the corresponding [Lullabot's ADR](https://architecture.lullabot.com/adr/20230929-drupal-build-steps/).
=> Issue #876: Run cache rebuild before Drupal database update

tasks/drupal.yml
As per https://architecture.lullabot.com/adr/20230929-drupal-build-steps/
```
vendor/bin/drush cache:rebuild --yes
vendor/bin/drush updatedb --yes
vendor/bin/drush config:import --yes || true
vendor/bin/drush config:import --yes
vendor/bin/drush deploy:hook --yes
vendor/bin/drush cache:rebuild -y
```
However we are missing that final `cache:rebuild` after running the `deploy:hook` command...
Also we should do a cache rebuild after turning off maintenance mode.
=> drupal:update is missing one final cache:rebuild after deploy:hook

scaffold/github/workflows/PantheonReviewAppsManualDDEV.yml
For the manual workflow of PantheonReviewApps, we need to use workflow_dispatch instead of other events.
=> Use workflow_dispatch in scaffold/github/workflows/PantheonReviewAppsManualDDEV.yml
