Lullabot/drainpipe

- README.md
- tasks/drupal.yml
This also changes the Drupal tasks to use an explicit variable for the site instead of relying on the CLI_ARGS
> Update the README with documentation on how to use this

- scaffold/gitlab/Pantheon.gitlab-ci.yml
Due to https://github.com/pantheon-systems/terminus/issues/2272
> Pin Terminus to 2.6.2

- tasks/drupal.yml
For things like specifying `--admin-password`.
> Pass command arguments from task to "drush site:install"

- README.md
- scaffold/github/actions/common/ddev/action.yml
- scaffold/github/actions/common/set-env/action.yml
- scaffold/github/actions/common/set-env/bash_aliases
- scaffold/github/actions/common/setup-git/action.yml
- scaffold/github/actions/common/setup-ssh/action.yml
- scaffold/github/actions/pantheon/review/action.yml
- scaffold/github/actions/pantheon/setup-terminus/action.yml
- scaffold/github/workflows/PantheonReviewApps.yml
- scaffold/github/workflows/PantheonReviewAppsDDEV.yml
- src/ScaffoldInstallerPlugin.php
> Add scaffolding for Pantheon Review Apps with GitHub Actions

- README.md
- tasks/javascript.yml
- tasks/sass.yml
Could be fancier, such as detecting the missing package to provide a better error, or automatically installing it? But this PR's changes help.
> Hint adding the Drainpipe node packages

- scaffold/github/actions/pantheon/clone-env/action.yml
Reverts Lullabot/drainpipe#81
Turns out this was actually slower :smile:
> Revert "Remove --size-only and --checksum from the rsync job"

- scaffold/github/actions/common/ddev/action.yml
See https://github.com/drud/ddev/issues/3686
> Pin DDEV to a specific version

- README.md
Adds small piece of documentation to define browser compatibility for a project.
> Add .browserslistrc documentation

- scaffold/github/actions/pantheon/clone-env/action.yml
- scaffold/github/actions/pantheon/review/action.yml
- scaffold/github/actions/pantheon/update/action.yml
- scaffold/github/workflows/PantheonReviewAppsDDEV.yml
…lock end>, but found '-' (syntax) #116
This pull request fixes YML syntax so that parsing is successful. 
Related to #116
> YAML Not Parsing

- scaffold/pantheon/pantheon.yml
- scaffold/pantheon/settings.pantheon.php
Bringing pantheon.settings.php file into compliance with phpcs Drupal standards.
> PHPCS Drupal Standards pantheon.settings.php

- scaffold/github/actions/common/ddev/action.yml
This is helpful as I currently can't run the actions locally with [act](https://github.com/nektos/act) due to the sudo commands in the installer script
> Use the apt repository for installing DDEV

- src/ScaffoldInstallerPlugin.php
> Fixes copying docker env file over

- scaffold/github/workflows/ComposerLockDiff.yml
Issue https://github.com/Lullabot/drainpipe/issues/181
> Issue #181: Fix composer-lock diff process when PR description newline

- scaffold/github/workflows/ComposerLockDiff.yml
Issue https://github.com/Lullabot/drainpipe/issues/181
> Issue #181: Fix composer-lock diff process when PR description new lines.

- tasks/drupal.yml
> Issue #190: Run cron once after drupal update steps.

- composer.json
- scaffold/env/env
See https://www.drupal.org/docs/develop/using-composer/using-drupals-composer-scaffold#toc_7
> Issue #183: Don't overwrite .env file with composer scaffold

- .github/workflows/TestSass.yml
- tasks/sass.yml
- tests/fixtures/sass/Taskfile.yml
- tests/fixtures/sass/style.scss
Fixes Sass compilation for npm, yarn classic, and yarn modern - as well as adding a test for all 3
> Fix Sass compilation and add a test

- .github/workflows/TestGitHubActions.yml
- README.md
- tasks/deploy.yml
Revert #242 due to https://github.com/Lullabot/drainpipe/actions/runs/5833175316/job/15820029674
> Revert #242

- README.md
- composer.json
- tasks/drupal.yml
See Issue #240
This changes the update procedure to mostly match https://www.drush.org/12.x/deploycommand/
> Issue #189: Change the update procedure to match drush deploy

- scaffold/tugboat/settings.tugboat.php.twig
> Issue #287: Fix coding standards violation in settings.tugboat.php

- scaffold/Taskfile.yml
> Add unblocking user 1 to the Taskfile scaffold as an example

- README.md
- scaffold/github/actions/common/ddev/action.yml
- Run tests in an existing repo e.g. `act -P ubuntu-latest=ghcr.io/catthehacker/ubuntu:runner-latest -j Static-Tests`
> Issue #403: Support local act runner

- .github/workflows/TestDDEV.yml
- scaffold/github/actions/common/ddev/action.yml
> Add a workaround for project being reconfigured as php project type

- scaffold/github/actions/pantheon/update/action.yml
https://github.com/Lullabot/drainpipe/issues/511
> Issue #511: Fixing aliases mapping for Github Update action.

- README.md
Fixes https://github.com/Lullabot/drainpipe/issues/500.
> Issue #500: Document disabling Pantheon integrated composer and autopilot.

- src/BinaryInstaller.php
- src/BinaryInstallerPlugin.php
This is extracted from https://github.com/Lullabot/drainpipe/pull/114/commits. It cleans up some phpdocs, and adds a typehint for a protected function.
> Fix docs and typos

- scaffold/tugboat/scripts/install-mysql-client.sh
In case it needs to be updated again.
> Add note about where MySQL GPG key is sourced from

- scaffold/github/actions/pantheon/review/action.yml
- scaffold/github/actions/pantheon/update/action.yml
Fixes https://github.com/Lullabot/drainpipe/issues/601 and https://github.com/Lullabot/drainpipe/issues/356
> Issue #601: Fix syntax error in update conditional.

- src/BinaryInstaller.php
- src/ScaffoldInstallerPlugin.php
Some code cleanups which are the remainder of https://github.com/Lullabot/drainpipe/pull/114 now that we have other PRs merging this in!
> More typehinting

- tasks/drupal.yml
fixes: #616 
This patch created by @alexanderpatriciop has been tested on multiple projects and does complete the deployment without failure
> Issue #616 - Fix Pantheon deploy error

- .pnp.cjs
This reverts commit c3e6bb191809637217d446c103120d0ee59e6c1e which was pushed directly to main
> Revert "560--fix-lerna"

- .github/workflows/TestBinaryInstaller.yml
- .github/workflows/ValidateTaskfile.yml
- .tugboat/steps/1-init.sh
- scaffold/tugboat/steps/1-init.sh.twig
- src/BinaryInstallerPlugin.php
> Issue #482: Update task to 3.38.0

- tasks/snapshot.yml
This changes short flags to long flags (https://architecture.lullabot.com/adr/20211006-avoid-command-aliases/) and enables multithreaded compression based on the number of available CPU cores.
> Enable multiple threads with xz

- drainpipe-dev/scaffold/.twig-cs-fixer.dist.php
This gets copied into the root of the project, and isn't referenced in vendor. This probably needs the web root path updated too.
> Fix wrong path to composer.json for TwigExtension cs-fixer

- .github/workflows/TestBinaryInstaller.yml
- .github/workflows/TestComposerLockDiff.yml
- .github/workflows/TestDDEV.yml
- .github/workflows/TestEnv.yml
- .github/workflows/TestFunctional.yml
- .github/workflows/TestGitHubActions.yml
- .github/workflows/TestMetapackages.yml
- .github/workflows/TestPHPUnit.yml
- .github/workflows/TestStatic.yml
- .github/workflows/TestTugboat.yml
https://github.com/ddev/ddev/issues/6628
> Workaround for ddev composer config broken in 1.23.5

- drainpipe-dev/scaffold/nightwatch/docker-compose.selenium.yaml
- #759 
- Remove version from docker-compose.selenium.yaml.
> Issue #759: Remove version from docker-compose.selenium.yaml.

- drainpipe-dev/scaffold/nightwatch/chrome.settings.php
- drainpipe-dev/scaffold/nightwatch/firefox.settings.php
- #757 
- Add Cache prefix on the chrome/firefox settings files.
> Issue #757: Add Cache prefix on the chrome/firefox settings files.

- .drainpipeignore
- .gitignore
- composer.json
> Issue #769: Add drainpipe-dev ignore folder.

- src/ScaffoldInstallerPlugin.php
- #628 
- Avoid rewriting the Tugboat folder completely.
> Issue #628: Avoid rewriting the Tugboat folder completely.

- scaffold/gitlab/ComposerLockDiff.gitlab-ci.yml
> 912: Rely on jq for JSON manipulation

- scaffold/github/actions/common/set-env/action.yml
- #944
- Make sure it is a branch to get the PR number on set-env action.
> Issue #944: Make sure it is a branch to get the PR number on set-env action.
